OF-1405: Validate XMPP domain field of S2S Tester in admin console
igniterealtime/Openfire pull request #2339
Opened 2023-11-15 15:21 UTC by guusdk

When the end-user provides an invalid value, try to correct for common mistakes, or show a nicer error message.

2023-11-15 15:29 UTC, akrherz approved these changes

2023-11-16 11:30 UTC, Fishbowler commented on xmppserver/src/main/webapp/server-connectiontest.jsp
> +    }
Could this cover conference, pubsub, etc?

2023-11-16 11:32 UTC, Fishbowler requested changes

2023-11-16 11:32 UTC, Fishbowler commented on xmppserver/src/main/webapp/server-connectiontest.jsp
> +            }
Testing for "potato.com/" results in a test for "potato.co"

2023-11-16 12:06 UTC, Fishbowler commented
:eyes:

2023-11-16 12:11 UTC, Fishbowler approved these changes

2023-11-16 12:16 UTC, merged