Add Persian Language
igniterealtime/Openfire pull request #2514
Opened 2024-08-26 14:22 UTC by telvideo

2024-08-26 14:26 UTC, akrherz commented
Why is there an unrelated addition of an ant github workflow?

2024-08-26 14:30 UTC, telvideo commented
Hello. I added it by mistake.

2024-08-26 14:32 UTC, telvideo commented
"I have added the Persian language."

2024-08-26 17:16 UTC, dwd commented
Looks good to me, although I can't do more than read the Farsi badly out loud (I only have rather poor Arabic). اوپن‌فایر looks OK at least!

2024-08-28 08:32 UTC, guusdk requested changes
Thanks for your contribution! This looks great! I've got a couple of requests:

- For people to be able to select this translation when they setup Openfire, it needs to be added to `xmppserver/src/main/webapp/setup/index.jsp`
- For people to be able to select this language after setup, it needs to be added to `xmppserver/src/main/webapp/server-locale.jsp`
- Excuse my ignorance, but is Farsi to be displayed left-to-right or right-to-left? If it is right-to-left, you'll need to add it to this method: `org.jivesoftware.util.LocaleUtils#isLocalizedTextRTL`
- I have created a ticket in our issue tracker for this change. Can you please rewrite your commit message to make a reference to [OF-2869](https://igniterealtime.atlassian.net/browse/OF-2869)? That way, it automatically pops up in our release notes.
- Can you please squash your commits into one commit? This will remove the file that was added by mistake from history.

2024-08-28 10:49 UTC, dwd commented
It is RTL, indeed.

2024-08-28 11:37 UTC, guusdk commented on xmppserver/src/main/webapp/server-locale.jsp
> +                <td>
I _think_ you need to use `fa` or `fa_IR` everywhere (here, and in other files) for this to work. You've been consistently using `fa` so I think you want to use that here, too.

2024-08-28 11:59 UTC, guusdk commented on xmppserver/src/main/webapp/server-locale.jsp
> +                    <a href="#" onclick="document.sform.localeCode[1].checked=true; return false;"><img src="images/language_fa.gif" alt="" /></a>
I do not think you need the image at all, here (this seems to be copied from the Chinese entry). The `img` tag should probably be removed. If it _is_ needed, than the file `images/language_fa.gif` should be added to this PR.

2024-08-28 12:00 UTC, guusdk commented on xmppserver/src/main/webapp/server-locale.jsp
> +                    <label for="fa">Persian (fa_IR)</label>
`fa_IR` should be `fa`, unless the translation is specific to Iranian (in which case all `fa`'s throughout this change should be changed to `fa_IR`).

2024-08-28 12:11 UTC, guusdk commented
Hey, I appreciate that you try to address every comment that I had, but I also see that you're struggling a bit. There is no shame in that. Would you prefer me fixing this PR for you? I'd be happy to help.

What is the most correct name for the translation that you added?

- Persian
- Persian (Iran)
- (something else)?

Would you like to be credited for this change? If so, what name would you like us to use?

2024-08-28 12:16 UTC, telvideo commented
> Hey, I appreciate that you try to address every comment that I had, but I also see that you're struggling a bit. There is no shame in that. Would you prefer me fixing this PR for you? I'd be happy to help.
> 
> What is the most correct name for the translation that you added?
> 
> * Persian
> * Persian (Iran)
> * (something else)?
> 
> Would you like to be credited for this change? If so, what name would you like us to use?

The most accurate name is "Persian (Iran)."

My name is Akbar Azimifar. I would be happy if my name is also mentioned as a contributor.

Sorry if I might not have fully understood the issue correctly.

2024-08-28 18:39 UTC, guusdk commented
I have now applied all of the little changes that I requested myself. That was easier than trying to explain to you what I think was needed - it should have saved us both some time!

Again, thank you for your translation! I would be grateful if you could give tomorrow's nightly build a test, to see if the translation works properly!

2024-08-28 18:40 UTC, akrherz commented
I am unsure about backporting this as the hope is we don't have any more 4.8 series releases?

2024-08-28 18:43 UTC, telvideo commented
> I have now applied all of the little changes that I requested myself. That was easier than trying to explain to you what I think was needed - it should have saved us both some time!
> 
> Again, thank you for your translation! I would be grateful if you could give tomorrow's nightly build a test, to see if the translation works properly!

That's right, I thought the same.

2024-08-28 18:49 UTC, merged

2024-08-28 19:03 UTC, guusdk commented
I have added the Persian language to our [Transifex project page](https://explore.transifex.com/igniterealtime/), for easier future updates. Sadly, it does not show all of the translated data yet. Hopefully, that automatically synchronizes in the future.

2024-08-29 08:53 UTC, guusdk commented
Nightly builds of Openfire that include this language are now available on http://www.igniterealtime.org/downloads/nightly_openfire.jsp

@telvideo would you mind testing one, to see if everything is in order?

2024-08-29 12:52 UTC, telvideo commented
> Nightly builds of Openfire that include this language are now available on http://www.igniterealtime.org/downloads/nightly_openfire.jsp
> 
> @telvideo would you mind testing one, to see if everything is in order?

![photo_2024-08-29_16-10-08](https://github.com/user-attachments/assets/e32f5390-a32e-4641-bfdd-390d30f2a534)
![photo_2024-08-29_16-10-25](https://github.com/user-attachments/assets/ccc6e12f-7453-495a-af76-e0e73e3b4620)
![photo_2024-08-29_16-10-48](https://github.com/user-attachments/assets/eea28896-5727-4c3d-a50f-d1622bbf478d)
![photo_2024-08-29_16-11-22](https://github.com/user-attachments/assets/b76383e1-04b6-45d2-9b90-be519aef2c35)
![photo_2024-08-29_16-11-53](https://github.com/user-attachments/assets/08ba5941-209b-4b3e-b43a-fd6bdb55d259)
![photo_2024-08-29_16-17-37](https://github.com/user-attachments/assets/8b332b4b-02ad-45cb-811c-cb12aae703b8)
![photo_2024-08-29_16-18-21](https://github.com/user-attachments/assets/195aaaef-71c5-4f30-9f15-45634859582a)
![photo_2024-08-29_16-18-39](https://github.com/user-attachments/assets/d3349dec-a05b-4fc9-a500-460964612c7a)
![photo_2024-08-29_16-19-14](https://github.com/user-attachments/assets/6245d366-ab37-4df0-93c5-2adba59652c2)



Hello, the installation was successful. It's good, but in some parts, the appearance has issues, and it doesn't display right-to-left correctly.

2024-08-30 09:57 UTC, guusdk commented
Thank you. If I understand your comment correctly, then it is currently usable, but should be improved. I have created a new ticket for this in our issue tracker: https://igniterealtime.atlassian.net/browse/OF-2870

If you happen to be available to apply these changes, then you would be more than welcome to. :)

2024-08-30 10:01 UTC, telvideo commented
> Thank you. If I understand your comment correctly, then it is currently usable, but should be improved. I have created a new ticket for this in our issue tracker: https://igniterealtime.atlassian.net/browse/OF-2870
> 
> If you happen to be available to apply these changes, then you would be more than welcome to. :)

Yes, it is usable and there are no issues, but it does need improvement.

I will definitely contribute.

Thank you.